Replaced exit 1 with fatal() function

diff --git a/email/patchman-email b/email/patchman-email
--- a/email/patchman-email
+++ b/email/patchman-email
@@ -187,6 +187,9 @@ usage() {
     echo "-h: Shows this help message and exits"
 }
 
+proc=$$
+trap 'exit 1' SIGUSR1
+
 # Checks if there are any parameters and if they start with "-"
 if [ $# -gt 0 ] && [[ $1 == -* ]]; then
     CONF="/etc/patchman/patchman-email.conf"
@@ -203,8 +206,7 @@ if [ $# -gt 0 ] && [[ $1 == -* ]]; then
         case $arg in
             a)
                 if [ ! -f $CONF ]; then
-                    echo "$(date '+%d/%m/%Y %R') [ERROR] Configuration file not found."
-                    exit 1
+                    fatal "$(date '+%d/%m/%Y %R') [ERROR] Configuration file not found."
                 else
                     DIR=$(getConfig General dir)
                     DATE=$(date +%Y%m%d)
@@ -226,8 +228,7 @@ if [ $# -gt 0 ] && [[ $1 == -* ]]; then
                 ;;
             H)
                 if [ ! -f $CONF ]; then
-                    echo "$(date '+%d/%m/%Y %R') [ERROR] Configuration file not found."
-                    exit 1
+                    fatal "$(date '+%d/%m/%Y %R') [ERROR] Configuration file not found."
                 else
                     DIR=$(getConfig General dir)
                     DATE=$(date +%Y%m%d)
@@ -239,8 +240,7 @@ if [ $# -gt 0 ] && [[ $1 == -* ]]; then
                 ;;
             T)
                 if [ ! -f $CONF ]; then
-                    echo "$(date '+%d/%m/%Y %R') [ERROR] Configuration file not found."
-                    exit 1
+                    fatal "$(date '+%d/%m/%Y %R') [ERROR] Configuration file not found."
                 else
                     DIR=$(getConfig General dir)
                     DATE=$(date +%Y%m%d)
@@ -254,8 +254,7 @@ if [ $# -gt 0 ] && [[ $1 == -* ]]; then
                         
                         email "$TAG"
                     else
-                        echo "$(date '+%d/%m/%Y %R') [ERROR] ${OPTARG}: Tag not found."
-                        exit 1
+                        fatal "$(date '+%d/%m/%Y %R') [ERROR] ${OPTARG}: Tag not found."
                     fi
                 fi
                 ;;
